version: "2"
services:
  php:
    build:
      context: .
    image: php-mysql-demo:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=demo_db
    volumes:
      - .:/var/www/html/
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
    ports:
      - "30001:80"
    container_name: php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=demo_db
    container_name: mysql-app
    volumes:
      - .:/var/www/html/
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend:
